# Generated by Django 3.2.7 on 2021-10-02 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_alter_position_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='price',
            field=models.PositiveIntegerField(blank=True),
        ),
    ]
