# Generated by Django 3.2.7 on 2021-10-06 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0007_auto_20211003_0130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='price',
            field=models.PositiveIntegerField(blank=True),
        ),
    ]
