# Generated by Django 3.2.7 on 2021-10-06 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0008_alter_position_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='price',
            field=models.FloatField(blank=True),
        ),
    ]
